udisk_price = input("扫描U盘的价格：")
gtf_price = input("扫描GTF卡的价格：")
card_reader_price = input("扫描读卡器的价格：")
network_cable_price = input("扫描网线的价格：")
print(".................................")
print("单号：DH202301010001")
print("时间：2023-01-01 08：56:15")
print(".................................")
print("名称         数量    单价    金额")
print("金士顿U盘8G    1", udisk_price, udisk_price, sep="    ")
print("胜创16GTF卡    1", gtf_price, gtf_price, sep="    ")
print("读卡器         1", card_reader_price, card_reader_price, sep="     ")
print("网线2米        1", network_cable_price, network_cable_price, sep="     ")
print(".................................")
print("总数：4          总额：103.00")
print("折后总额：103.00")
print("实收：103.00     找零：0.00")
print("收银：管理员")
print(".................................")
