jasypt.encryptor.password: ${JASYPT_ENCRYPTOR_PASSWORD}

server:
  port: 9898

spring:
  application:
    name: ${app_name:examples-cache}
  cache:
    type: redis
  redis:
    cluster:
      nodes: ${REDIS_CLUSTER}
    password: ${REDIS_PWD}

logging:
  level:
    com.alicp.jetcache: trace
    org.springframework.cache: trace