server:
  port: 6363
database:
  dialect: mariadb  # 或者 mariadb
  postgres:
    url: postgres://root:root@192.168.11.130/sso?sslmode=disable
  mariadb:
    url: root:root@tcp(192.168.11.66:3306)/sso?parseTime=true
redis:
  url: redis://192.168.11.66:6379
  pwd: redis
  db: 0
security:
  secret: examples-project-go