server:
  port: 12462

spring:
  main:
    allow-circular-references: true

dubbo:
  scan:
    base-packages: org.diguapao.cloud.inventory.service
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 22462
  registry:
    address: nacos://127.0.0.1:8848?username=${spring.cloud.nacos.username}&password=${spring.cloud.nacos.password}
    username: ${spring.cloud.nacos.username} # 似乎没效果，需要在address的url上上配置
    password: ${spring.cloud.nacos.password} # 似乎没效果，需要在address的url上上配置
    parameters:
      namespace: ${spring.cloud.nacos.config.namespace}
      username: ${spring.cloud.nacos.username} # 似乎没效果，需要在address的url上上配置
      password: ${spring.cloud.nacos.password} # 似乎没效果，需要在address的url上上配置
    server: ${spring.application.name}
  metadata-report:
    username: ${spring.cloud.nacos.username} # 似乎没效果，需要在address的url上上配置
    password: ${spring.cloud.nacos.password} # 似乎没效果，需要在address的url上上配置
    address: ${dubbo.registry.address}
    parameters:
      namespace: ${spring.cloud.nacos.config.namespace}
  config-center:
    username: ${spring.cloud.nacos.username} # 似乎没效果，需要在address的url上上配置
    password: ${spring.cloud.nacos.password} # 似乎没效果，需要在address的url上上配置
    namespace: ${spring.cloud.nacos.config.namespace}
    address: ${dubbo.registry.address}